// Measures the Text glyphs and writes packages/core/src/kerning.ts: the advance
// of every character and the kerning pairs left after the bearings took their
// share. Run after changing a letter, a digit, a mark or textSpacing.ts:
//
//   pnpm kerning
//
// The layout only reads the file; kerning.test.ts fails while it is stale.

import { writeFileSync } from "node:fs";
import { measureText } from "../packages/core/dist/textMeasure.js";

const { metrics, kerning } = measureText();
const key = (ch: string) => JSON.stringify(ch);
const lines = [
  "// Generated by scripts/build-kerning.ts from the glyph data. Do not edit by hand:",
  "// change the glyphs or textSpacing.ts and run `pnpm kerning`.",
  "",
  "/** [viewBox x, advance] of each character Text draws, in glyph units, bearings included. */",
  "export const TEXT_METRICS: Readonly<Record<string, readonly [number, number]>> = {",
  ...Object.entries(metrics).map(([ch, [x, w]]) => `  ${key(ch)}: [${x}, ${w}],`),
  "};",
  "",
  "/** Kerning pairs: how far the second character moves after the first, glyph units. */",
  "export const TEXT_KERNING: Readonly<Record<string, Readonly<Record<string, number>>>> = {",
  ...Object.entries(kerning).map(([a, row]) =>
    `  ${key(a)}: { ${Object.entries(row).map(([b, k]) => `${key(b)}: ${k}`).join(", ")} },`),
  "};",
  "",
];
writeFileSync(new URL("../packages/core/src/kerning.ts", import.meta.url), lines.join("\n"));
const pairs = Object.values(kerning).reduce((n, row) => n + Object.keys(row).length, 0);
console.log(`kerning.ts: ${Object.keys(metrics).length} characters, ${pairs} pairs`);
